### ISSUE TITLE
SKR IpRange deletion prevention should work when CR's use unspecified (default) IpRange

### ISSUE THREAD

**Issue by dushanpantic** [kyma-project/cloud-manager#327]
When a custom resource (e.g. AwsNfsVolume) does not specify the desired IpRange, it will use a default one.
The IpRange deletion prevention mechanism should handle this case, where CR's `.spec.IpRange` is empty

**Comment by tmilos77** [comment]
This should have been fixed in #328 by https://github.com/kyma-project/cloud-manager/pull/328/files#diff-0232372c92427323f7964464562a01239b44b36242623dd4f4bec8fa54524b70R72

Still has to be tested and verified.
